version: 2.1

jobs:
  tests:
    docker:
      - image: alpine@sha256:769fddc7cc2f0a1c35abb2f91432e8beecf83916c421420e6a6da9f8975464b6 # alpine:3.9.4
    steps:
      - run:
          name: Install dependencies
          command: |
            apk --no-progress add --update \
              make qemu-system-x86_64 socat coreutils bc util-linux \
              gcc musl-dev linux-headers flex bison curl
      - checkout
      - run:
          name: Compile kernel and our sources
          command: make build -j4
      - run:
          name: Run power-off loop in background
          command: make power-off-loop
          background: true
      - run:
          name: Run tests
          command: make test

workflows:
  version: 2
  main:
    jobs:
      - tests
